name: Push docs

on:
  push:
    branches:
      - master

jobs:
  sphinx_docs_to_gh-pages:
    runs-on: ubuntu-latest
    name: Sphinx docs to gh-pages
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Installing the Documentation requirements
        run: |
          pip3 install .[docs]
      - name: Installing the library
        shell: bash -l {0}
        run: |
          pip3 install .
      - name: Running the Sphinx to gh-pages Action
        uses: uibcdf/action-sphinx-docs-to-gh-pages@v2.0.0
        with:
          branch: main
          dir_docs: docs
          sphinxapiopts: '--separate -o . ../'
          sphinxapiexclude: '../*setup* ../*.ipynb'
          sphinxopts: ''